---
- name: Command Module
  hosts: localhost
  become: true
  tasks:
     - script: /usr/local/src/uptime.sh
     - shell: uptime >> uptime.log
       args:
         chdir: /tmp
     - command: uname -a 

     - name: install pexpect
       pip:
         name: pexpect
         state: latest

     - expect:
        command: passwd lucia
        responses:
          (?i)password: "lucia123"
