---
- hosts: localhost
  tasks:
    - include_vars: variables.yml
    - debug:
         msg:  "Hostname {{ ansible_hostname }} FQDN {{ ansible_fqdn }}"
    - command: uptime
      register: exit
    - debug:
         var: exit
    - fail:
         msg: "Number is not 10"
      when: number != 10
    - pause:
         prompt: "Check the APP"
         seconds: 2
    - assert:
         msg: "Number between 0 and 100"
         that:
           - number <=100
           - number > 0
