---
- name: Yum Module
  hosts: 192.168.15.3
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Update Packages
      yum:
        name: '*'
        state: latest
