---
- name: install and configure mariadb
  hosts: all
  remote_user: alfonso
  become: yes
  become_method: sudo

  tasks:
  - name: looping over files and the copy
    copy: src={{item}} dest=/tmp/loops
    with_fileglob: "/tmp/*.conf"

  - name: do until someting
    shell: echo hello
    register: output
    retries: 5
    delay: 5
    until: output.stdout.find('hello') != -1
