---
- name: install and configure mariadb
  hosts: all
  remote_user: alfonso
  become_method: sudo
  become: yes

  vars:
          mariadb_port: 3306

  tasks:
    - include: selinux.yml

    - block:
       - name: install mariadb
         yum: 
           name: mariadb-server 
           state: latest

       - name: create mysql configuration file
         template: 
           src: mariadb-server.cnf.j2 
           dest: /etc/my.cnf.d/mariadb-server.cnf
           backup: yes
         notify: restart mariadb

       - name: create mariadb log file
         file: 
           path: /var/log/mariadb/mariadb.log 
           state: touch 
           owner: mysql 
           group: mysql 
           mode: 644

       - name: start mariadb service
         systemd: 
          name: mariadb 
          state: started 
          enabled: yes

      when: ansible_os_family=="RedHat"

  handlers: 
  - name: restart mariadb
    systemd: 
      name: mariadb 
      state: restarted

