---
- name: Install python bindings for SE Linux
  yum:
    name:
      - python3-libselinux
      - python3-libsemanage

    state: latest

- name: test to see if selinux is running
  command: getenforce
