---
- name: Playbook for register
  hosts: localhost
  tasks:
     - name: Uptime command
       command: uptime
       register: register_uptime

     - name: Check variable
       debug:
          var: register_uptime.stdout
       when: register_uptime | changed
