---
- name: install nginx
  yum:
    name: nginx
    state: latest

- name: create nginx configuration file
  template:
     src: nginx.cnf.j2
     dest: /etc/nginx/nginx.cnf
  notify: restart nginx

- name: Insert Index Page
  template:
     src: index.html
     dest: /usr/share/nginx/html/index.html

- name: start Nginx
  service:
     name: mariadb
     state: started
     enabled: yes

