---
- name: install nginx
  yum:
    name: nginx
    state: latest

- name: create nginx configuration file
  template:
     remote_src: nginx.conf.j2
     dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Insert Index Page
  template:
     remote_src: index.html
     dest: /usr/share/nginx/html/index.html

- name: start Nginx
  service:
     name: mariadb
     state: started
     enabled: yes

